apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: gcr.io/jackzampolin-web/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
